# Generated by Django 3.2 on 2024-03-21 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_auto_20240321_0710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='description',
        ),
    ]
